import { Team } from "./types";

function nationalTeam(
  id: string,
  name: string,
  flagCode: string,
  attack: number,
  midfield: number,
  defense: number
): Team {
  const overall = Math.round(((attack + midfield + defense) / 3) * 10) / 10;
  return {
    id,
    name,
    rating: overall.toFixed(1).replace(".", ","),
    attack,
    midfield,
    defense,
    flag: `https://flagcdn.com/w80/${flagCode}.png`,
  };
}

/** Todas as 60 seleções masculinas do EA FC 26 (ATT / MID / DEF — fcratings.com) */
export const NATIONAL_TEAMS: Team[] = [
  nationalTeam("france", "França", "fr", 87, 85, 85),
  nationalTeam("england", "Inglaterra", "gb-eng", 86, 85, 83),
  nationalTeam("sweden", "Suécia", "se", 86, 77, 75),
  nationalTeam("brazil", "Brasil", "br", 85, 83, 84),
  nationalTeam("spain", "Espanha", "es", 85, 86, 83),
  nationalTeam("portugal", "Portugal", "pt", 84, 86, 84),
  nationalTeam("argentina", "Argentina", "ar", 84, 83, 79),
  nationalTeam("germany", "Alemanha", "de", 82, 84, 84),
  nationalTeam("italy", "Itália", "it", 82, 83, 83),
  nationalTeam("belgium", "Bélgica", "be", 82, 82, 78),
  nationalTeam("poland", "Polônia", "pl", 82, 75, 78),
  nationalTeam("netherlands", "Holanda", "nl", 80, 83, 83),
  nationalTeam("norway", "Noruega", "no", 80, 81, 75),
  nationalTeam("ivory-coast", "Costa do Marfim", "ci", 80, 78, 78),
  nationalTeam("morocco", "Marrocos", "ma", 80, 78, 78),
  nationalTeam("colombia", "Colômbia", "co", 79, 79, 78),
  nationalTeam("senegal", "Senegal", "sn", 79, 80, 77),
  nationalTeam("turkiye", "Turquia", "tr", 79, 80, 78),
  nationalTeam("ukraine", "Ucrânia", "ua", 79, 76, 76),
  nationalTeam("croatia", "Croácia", "hr", 78, 81, 77),
  nationalTeam("mexico", "México", "mx", 78, 75, 75),
  nationalTeam("czechia", "Tchéquia", "cz", 78, 75, 75),
  nationalTeam("denmark", "Dinamarca", "dk", 78, 79, 78),
  nationalTeam("uruguay", "Uruguai", "uy", 78, 79, 79),
  nationalTeam("bosnia", "Bósnia e Herzegovina", "ba", 78, 70, 73),
  nationalTeam("congo-dr", "RD Congo", "cd", 78, 71, 75),
  nationalTeam("egypt", "Egito", "eg", 78, 73, 70),
  nationalTeam("ghana", "Gana", "gh", 78, 75, 73),
  nationalTeam("japan", "Japão", "jp", 78, 78, 76),
  nationalTeam("austria", "Áustria", "at", 77, 78, 79),
  nationalTeam("canada", "Canadá", "ca", 77, 74, 74),
  nationalTeam("hungary", "Hungria", "hu", 77, 74, 74),
  nationalTeam("scotland", "Escócia", "gb-sct", 77, 78, 74),
  nationalTeam("switzerland", "Suíça", "ch", 77, 79, 76),
  nationalTeam("usa", "Estados Unidos", "us", 77, 79, 77),
  nationalTeam("algeria", "Argélia", "dz", 75, 76, 76),
  nationalTeam("ecuador", "Equador", "ec", 73, 76, 78),
  nationalTeam("korea", "Coreia do Sul", "kr", 79, 74, 74),
  nationalTeam("paraguay", "Paraguai", "py", 74, 75, 76),
  nationalTeam("wales", "País de Gales", "gb-wls", 74, 76, 74),
  nationalTeam("saudi-arabia", "Arábia Saudita", "sa", 74, 74, 71),
  nationalTeam("new-zealand", "Nova Zelândia", "nz", 74, 69, 69),
  nationalTeam("iran", "Irã", "ir", 73, 72, 72),
  nationalTeam("romania", "Romênia", "ro", 72, 72, 72),
  nationalTeam("ireland", "Irlanda", "ie", 75, 71, 74),
  nationalTeam("tunisia", "Tunísia", "tn", 70, 72, 72),
  nationalTeam("iceland", "Islândia", "is", 68, 73, 69),
  nationalTeam("australia", "Austrália", "au", 69, 68, 71),
  nationalTeam("cape-verde", "Cabo Verde", "cv", 69, 69, 71),
  nationalTeam("panama", "Panamá", "pa", 70, 70, 69),
  nationalTeam("south-africa", "África do Sul", "za", 70, 69, 70),
  nationalTeam("uzbekistan", "Uzbequistão", "uz", 70, 67, 71),
  nationalTeam("haiti", "Haiti", "ht", 70, 69, 69),
  nationalTeam("qatar", "Catar", "qa", 71, 68, 66),
  nationalTeam("northern-ireland", "Irlanda do Norte", "gb-nir", 66, 70, 70),
  nationalTeam("curacao", "Curaçao", "cw", 66, 69, 69),
  nationalTeam("finland", "Finlândia", "fi", 75, 69, 64),
  nationalTeam("jordan", "Jordânia", "jo", 66, 67, 66),
  nationalTeam("indonesia", "Indonésia", "id", 64, 66, 71),
  nationalTeam("iraq", "Iraque", "iq", 63, 66, 64),
];
